SUPABASE_URL = "https://ensxqllikajohvuoaogb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuc3hxbGxpa2Fqb2h2dW9hb2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNTI4MDQsImV4cCI6MjA4MDkyODgwNH0.WMeduJZ5evnTQ_m9dELGhzI3OccAyDxvgsTvuXZbpao"
